Module2 task1
htmlacademy-ecmascript/1968829-cinemaddict-16 pull request #5
Opened 2022-01-07 21:00 UTC by mmakeychev91

2022-01-08 15:11 UTC, Ch1sKey requested changes

2022-01-08 15:11 UTC, Ch1sKey commented on src/view/detail-info-popup.js
> +                ${genresTemplate()}
Еще про map. 
Например, тут можно было бы заменить на:
```
<td class="film-details__cell">
  ${callGenerateGenre.map(genre => `<span class="film-details__genre">${genre}</span>`).join('')}
</td>
```
Получается значительно декларативнее, чем функции с запутанной и похожей логикой.

2022-01-08 15:11 UTC, Ch1sKey commented on src/view/film-card.js
> +  const {title, poster, rating, releaseDate, runtime, genres, description, comments, isWatchlist, isWatched, isFavorite} = card;
Вообще можно реструктуризировать прямо там. где аргумент объявляется. 
```
export const createFilmCardTemplate = ({
  title,
  poster,
  rating,
  releaseDate,
  runtime,
  genres,
  description,
  comments,
  isWatchlist,
  isWatched,
  isFavorite
 }) => {
...
}
```

2022-01-08 15:11 UTC, Ch1sKey commented on src/mock/film.js
> +const generateBoolean = () => {
Оригинально, но по-моему избыточная функция. Можно сразу использовать `Math.random() > 0.5`

2022-01-08 15:53 UTC, mmakeychev91 commented on .eslintignore
> +main.js
забыл убрать, сейчас

2022-01-08 15:59 UTC, mmakeychev91 commented on src/mock/film.js
> +  const n = getRandomInteger(3, 3);
да, похоже, исправил

2022-01-08 16:08 UTC, mmakeychev91 commented on src/mock/film.js
> +  if (genreQuantity === 'one') {
да, согласен, исправил. отличное замечание, надо взять в постоянную практику

2022-01-08 16:10 UTC, mmakeychev91 commented on src/mock/film.js
> +const generateDiscription = () => {
исправил

2022-01-08 16:11 UTC, mmakeychev91 commented on src/mock/film.js
> +const lorem = [
готово

2022-01-08 16:42 UTC, mmakeychev91 commented on src/mock/film.js
> +const generateBoolean = () => {
согласен, исправил

2022-01-08 16:57 UTC, mmakeychev91 commented on src/view/film-card.js
> +  const {title, poster, rating, releaseDate, runtime, genres, description, comments, isWatchlist, isWatched, isFavorite} = card;
круто! исправил

2022-01-08 17:50 UTC, mmakeychev91 commented on src/view/detail-info-popup.js
> +                ${genresTemplate()}
не посмотришь, исправил

2022-01-08 18:48 UTC, mmakeychev91 commented on src/view/detail-info-popup.js
> +  const commentTemplate = () => {
да, через map гораздо удобнее и изящнее. спасибо! исправил

2022-01-09 12:33 UTC, Ch1sKey approved these changes

2022-01-09 12:34 UTC, merged